[project]
name = "playground-ml"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "playground",
]

[tool.uv.workspace]
members = ["playground"]

[tool.uv.sources]
playground = { workspace = true }
