[project]
name = "playground"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "httpx<0.28",
    "langchain>=0.3.12",
    "langchain-aws>=0.2.9",
    "langchain-cli>=0.0.35",
    "langserve>=0.3.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.3",
]
